### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by cinthyadavis** [PeculiarVentures/fortify-releases#22] opened 2024-11-26 20:45 UTC
Reader name: Bit4id miniLector-s
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "8F3EB2D7B8A265CCEB2C2BE5F6B5D63CC9D6F457"
   }],
   "drivers": [{
   	"id": "8F3EB2D7B8A265CCEB2C2BE5F6B5D63CC9D6F457",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by Kharya1337** [comment] 2024-11-27 10:04
@cinthyadavis This is a dupe of https://github.com/PeculiarVentures/fortify-releases/issues/21 .
Can you please take a look at https://github.com/PeculiarVentures/fortify-releases/issues/21#issuecomment-2501118947

**Closed as completed by Kharya1337** 2024-11-27 10:04 UTC
