### ISSUE TITLE
Añadir soporte para el token '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3'

### ISSUE THREAD

**Issue by Priss1991** [PeculiarVentures/fortify-releases#9] opened 2024-09-16 16:40 UTC
Reader name: HID Global OMNIKEY 3x21 Smart Card Reader
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "7533318CDC57E4A3507F94CFE374E2884AA811DD"
   }],
   "drivers": [{
   	"id": "7533318CDC57E4A3507F94CFE374E2884AA811DD",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by Kharya1337** [comment] 2024-11-21 11:52
Dupe of https://github.com/PeculiarVentures/fortify-releases/issues/10

**Closed by Kharya1337** 2024-11-21 11:52 UTC
