### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by joseandresquiros** [PeculiarVentures/fortify-releases#4] opened 2024-09-07 20:24 UTC
Reader name: Bit4id miniLector-s
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "D94931A1E33E6A1BDD50B4948F406010CA2B5355"
   }],
   "drivers": [{
   	"id": "D94931A1E33E6A1BDD50B4948F406010CA2B5355",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by Kharya1337** [comment] 2024-11-21 11:53
Thank you for the bug, if you could provide additional information we would love to try to make this card work without error.

We need to know:

Who makes the card?
What middleware is used with the card?
What is the name and path of the PKCS#11 library in that middleware?

Also we have done some more exploration, it seems that MAYBE this card works with:
`/usr/local/lib/libASEP11.dylib`

If so adding this one card to `cards.json` should in theory make this card work.

```
{
	"cards": [
	  {
		"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
		"name": "Central Bank of Costa Rica smartcard",
		"driver": "29a2bd60c4b841c686be68d2874c0c02"
	  }
	]
}
```
Unfortunately without a user who can work with us to confirm the above we can not add this to the formal definition of supported cards.

**Comment by Kharya1337** [comment] 2024-11-21 11:53
Dupe of https://github.com/PeculiarVentures/fortify-releases/issues/3

**Closed** 2024-11-21 11:53 UTC
